"""student parent accounts

Revision ID: 07accd5a77df
Revises: 0f8f7de4ca6f
Create Date: 2026-07-11 08:57:41.990841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '07accd5a77df'
down_revision: Union[str, None] = '0f8f7de4ca6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation_type', sa.String(length=20), server_default='', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('parent_students', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('relation_type')

    # ### end Alembic commands ###
